### ISSUE TITLE
추가적인 마크업 작업 + 반응형

### ISSUE THREAD

**Issue by danmin20** [woowa-techcamp-2021/store-7#119]
## 📑 체크리스트

> 수행해야 할 체크리스트

- [x] 마이페이지
- [x] 백오피스
- [x] 카테고리

### 반응형
- [x] 마이페이지
- [x] 장바구니
- [x] 주문결제
- [x] 메인
- [x] 카테고리
- [x] 헤더
- [x] 푸터
- [x] 결제완료

## ⏰ 예상 소요 시간 [단위: MD]

2D

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- 예쁘게 만들기 희희

**Comment by danmin20** [comment]
@LeagueLugas 백오피스 대시보드 완료되면 체크 후 닫아주세요~!

**Comment by HobinLee** [comment]
다들 너무 고생하셨습니다 ㅠㅠ
