### ISSUE TITLE
버그는 아니지만.. 모바일 환경에서 좌우 스크롤..!

### ISSUE THREAD

**Issue by jiyong1** [woowa-techcamp-2021/store-7#160]
## :hammer: 기능 설명

반응형으로 구현하셨는데 모바일 환경에서 좌우로 스크롤이 돼서.. 수정하시면 좋을 것 같은데 어떻게 생각하시나요?!

![스크린샷 2021-08-27 오후 2 17 11](https://user-images.githubusercontent.com/62745840/131075660-d4e68e85-8edc-46c1-b63c-4e5b6fe62ffd.png)

## 📑 체크리스트

> 수행해야 할 체크리스트

- [ ] 좌우 스크롤

## ⏰ 예상 소요 시간 [단위: MD]

1MD

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

**Comment by jjunyjjuny** [comment]
해결되었습니다! #204  #209
