### ISSUE TITLE
스마트 레이어 서버 카테고리 위치 버그

### ISSUE THREAD

**Issue by ag502** [woowa-techcamp-2021/store-7#165]
## ⚠️ 버그 설명

버그 설명
의도하셨을 수도 있지만 스마트 레이어의 서브 카테고리 위치가 계속 이동하는 거 같습니다. 😁

디자인이 너무 이쁘네요. 대단하십니다 👏👏👏

<선택> 이해를 돕기 위한 스크린샷을 첨부해주세요.
![Aug-27-2021 14-19-35](https://user-images.githubusercontent.com/35404137/131075909-147e969a-5f40-48f0-9afd-09e6a2abcfeb.gif)

## 📑 체크리스트

> 해결해야하는 버그 체크리스트

- [ ] 체크 사항 1
- [ ] 체크 사항 2
- [ ] 체크 사항 3
- [ ] 체크 사항 4

## 🚧 주의 사항

> 버그를 해결할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

**Comment by danmin20** [comment]
#161 과 동일
