### ISSUE TITLE
로그인 하지 않았을 때 마이페이지를 URL로 접근하면 에러가 뜹니다.

### ISSUE THREAD

**Issue by jonghopark95** [woowa-techcamp-2021/store-7#167]
## ⚠️ 버그 설명

로그인 하지 않았을 때 마이페이지를 URL로 접근하면 에러가 뜹니다.

<img width="780" alt="스크린샷 2021-08-27 오후 2 24 30" src="https://user-images.githubusercontent.com/19240202/131076221-03103d63-5fc1-4f89-b00f-752d1457174c.png">

## 📑 체크리스트

> 해결해야하는 버그 체크리스트

- [ ] 로그인 하지 않았을 때 마이페이지 접근 막기

## 🚧 주의 사항

> 버그를 해결할 때 유의깊게 살펴볼 사항

- X

**Comment by danmin20** [comment]
#156 과 동일
