### ISSUE TITLE
[bug] 비회원 주문 완료 후 주문내역 보기 버튼 먹통

### ISSUE THREAD

**Issue by cothis** [woowa-techcamp-2021/store-7#175]
## ⚠️ 버그 설명
![스크린샷 2021-08-27 오후 2 39 59](https://user-images.githubusercontent.com/50898502/131077668-550e6e6b-7295-4fdf-9ffe-f2235019b89b.png)

**Comment by danmin20** [comment]
주문내역 페이지 구현 완료
