### ISSUE TITLE
[bug] 검색어로 검색 시, 검색 성공률이 50프로정도 됩니다.

### ISSUE THREAD

**Issue by cothis** [woowa-techcamp-2021/store-7#177]
## ⚠️ 버그 설명

같은 검색어로 검색하는데 어떨땐 나오고 어떨땐 무한로딩이에요
그리고 콘솔창에서 안녕? 무서워요
![스크린샷 2021-08-27 오후 2 42 31](https://user-images.githubusercontent.com/50898502/131077892-1fcd00ac-2420-42e7-9e7a-c9b31abafcea.png)

**Comment by danmin20** [comment]
#155 와 동일
