### ISSUE TITLE
[BUG] 물품에 글자가 들어가도 주문까지 작동하는데 마이페이지에서 주문목록에서 안보입니다.

### ISSUE THREAD

**Issue by juyoungpark718** [woowa-techcamp-2021/store-7#179]
## ⚠️ 버그 설명

버그 설명

<선택> 이해를 돕기 위한 스크린샷을 첨부해주세요.

## 📑 체크리스트

> 해결해야하는 버그 체크리스트

- [ ] 체크 사항 1
- [ ] 체크 사항 2
- [ ] 체크 사항 3
- [ ] 체크 사항 4

## 🚧 주의 사항

> 버그를 해결할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

**Comment by danmin20** [comment]
물품에 글자가 들어갔다는 게 혹시 어떤 의미일까요....? ㅜㅜ

**Comment by danmin20** [comment]
혹시 개수에 문자를 넣는다는 말씀이실까요? 그 부분은 해결되었으니 맞다면 이슈 닫도록 하겠습니다!
