### ISSUE TITLE
[BUG] 검색 기능 버그

### ISSUE THREAD

**Issue by Seogeurim** [woowa-techcamp-2021/store-7#184]
## ⚠️ 버그 설명

검색어 입력 후 새로고침을 해야 그 결과가 보이는 버그가 있습니다. 그리고 검색 결과가 있을 때와 없을 때 검색어의 위치가 다르게 나옵니다.

### 사용 브라우저

크롬

### 버그 발생 순서

1. 검색어를 입력합니다.
2. [bug] 계속 로딩이 됩니다.
3. 새로고침을 합니다.
4. 검색 결과가 잘 나옵니다.
5. 검색 결과가 있을 때와 없을 때의 레이아웃을 확인합니다.

> 바로 잘 나오는 경우도 있고 아닌 경우도 있는 것 같습니다.

<선택> 이해를 돕기 위한 스크린샷을 첨부해주세요.

![image](https://user-images.githubusercontent.com/22045163/131078936-c290bae1-7a71-4a56-a78d-a304b67619c5.png)
![image](https://user-images.githubusercontent.com/22045163/131078946-2ceb81c5-eb24-452f-ae12-e043e0fb19e4.png)

## 📑 체크리스트

> 해결해야하는 버그 체크리스트

- [ ] 체크 사항 1
- [ ] 체크 사항 2
- [ ] 체크 사항 3
- [ ] 체크 사항 4

## 🚧 주의 사항

> 버그를 해결할 때 유의깊게 살펴볼 사항

- 주의 사항 1
- 주의 사항 2

**Comment by danmin20** [comment]
#155 와 동일
