### ISSUE TITLE
[Bug] 검색 기능 버그

### ISSUE THREAD

**Issue by LeagueLugas** [woowa-techcamp-2021/store-7#187]
## ⚠️ 버그 설명
검색칸에서 엔터를 누를 때 서버로 요청을 안보내진다

## 📑 체크리스트

> 해결해야하는 버그 체크리스트

- [ ] 검색 인풋 핸들러 재확인

## 🚧 주의 사항

> 버그를 해결할 때 유의깊게 살펴볼 사항

- 머리카락이 빠질 가능성이 높다

**Comment by danmin20** [comment]
fix 완료
