### ISSUE TITLE
[1차 데모 피드백]

### ISSUE THREAD

**Issue by HobinLee** [woowa-techcamp-2021/store-7#44]
## :hammer: 1차 데모 피드백

1차 데모에서 시연하면서 개선했으면 하는 점들을 적어주세요~!

## 📑 체크리스트

> 수행해야 할 체크리스트

- [x] 찜하기 마우스 호버시에 클릭한 색상과 동일해서 혼란을 줄 것 같습니다. 조금더 투명한 색으로 처리하면 좋을것같아요 (@jjunyjjuny )
- [ ] 헤더 가테고리 리스트 부분 하단에 사용되지 않는 스크롤바가 표시됩니다.
- [ ] 체크 사항 3
- [ ] 체크 사항 4

**Comment by danmin20** [comment]
스크롤바는 헤더관련 이슈에도 작성되어있으니 이 이슈는 닫도록 하겠습니다!
